[versions]
minecraft = "1.0.0"
feather-mappings = "1.0.0-client+build.20"
nests = "1.0.0-client+build.1"
fabric-loader = "0.15.1"
loom = "1.3-SNAPSHOT"
loom-vineflower = "1.11.0"
fabric-asm = "v2.3.3"
zt-zip = "1.16"
slf4j-api = "2.0.9"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
feather-mappings = { module = "net.ornithemc:feather", version.ref = "feather-mappings" }
nests = { module = "net.ornithemc:nests", version.ref = "nests" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-asm = { module = "com.github.Minecraft-Java-Edition-Speedrunning:fabric-asm", version.ref = "fabric-asm" }
zt-zip = { module = "org.zeroturnaround:zt-zip", version.ref = "zt-zip" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
ploceus = { id = "ploceus", version.ref = "loom" }
loom-vineflower = { id = "io.github.juuxel.loom-vineflower", version.ref = "loom-vineflower" }
